version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      bash -c "jupyter lab --allow-root --ip=0.0.0.0 --no-browser --NotebookApp.token=''"
    ports:
      - 8888:8888
    volumes:
      - ./:/app
